# Generated by Django 4.0.3 on 2022-04-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован?'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок'),
        ),
    ]
